### ISSUE TITLE
Question about safety

### ISSUE THREAD

**Issue by d-e-s-o** [Xudong-Huang/rcu_cell#1]
I mainly have a question as I am trying to understand how your code can be safe. Consider the following code sequence of events:

```rust
        let t = RcuCell::new(Some(10));
thread 1:
        let x = t.read();

thread 2:
        t.try_lock().unwrap().update(Some(3));
```

And now consider the following scheduling sequence:
```rust
let t = RcuCell::new(Some(10));
let x = t.read();
  > pub fn read(&self) -> Option<RcuReader<T>> {
  >     self.link.get()
  > }
    > #[inline]
    > fn get(&self) -> Option<RcuReader<T>> {
    >     loop {
    >         let ptr = self.0.ptr.load(Ordering::Acquire);
    >                                                            <----- we get preempted here!
    >         match self._conv(ptr) {
    >             None => return None,
    >             Some(p) => {
    >                 // the old data is drop we should re-read the data again!
    >                 if p.inc_ref() == 0 {
    >                     continue;
    >                 }
    >                 return Some(RcuReader {
    >                     inner: NonNull::new(p as *const _ as *mut _).expect("null shared"),
    >                 });
    >             }
    >         }
    >     }
    > }
```

So now thread 2 runs and it updates the data. As part of this update it ends up in:

```rust
t.try_lock().unwrap().update(None);
  > pub fn update(&mut self, data: Option<T>) {
  >     // the RcuCell is acquired now
  >     let old_link = self.link.swap(data);
  >     if let Some(old) = old_link {
  >         let cnt = old.inc_ref();
  >         assert!(cnt > 0);
  >         let ptr = NonNull::new(old as *const _ as *mut _).expect("null Shared");
  >         let d = RcuReader::<T> { inner: ptr };
  >         d.unlink();
  >     }
  > }
```

What I understand happens here is that the `RcuReader` is reinstantiated and then dropped (it is `unlink`ed and then dropped, resulting in two `dec_ref` calls, decrementing the reference count to zero and, hence, deallocating the `RcuInner`).

So now thread 1 runs again. It converts the pointer into into an `RcuInner` and then calls `inc_ref`. However, the memory has been freed. So aren't we accessing dead memory at this point, resulting in memory unsafety? Am I missing something here?

**Comment by Xudong-Huang** [comment]
yes, you are right. this is definitely a bug. I will try to fix this as soon as possible. Thanks!

**Comment by Xudong-Huang** [comment]
now I add a read lock to protect the ptr. the update would wait until the read lock bit cleared, at that time the memory reclaim is safe. this fix also slow the read a little bit.

**Comment by d-e-s-o** [comment]
Awesome, the solution seems fine based on a cursory glance! Thanks for the quick fix.
